spring:
  application:
    name: Kakao_CloneCoding_Backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kakao_clone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: choi76003347! # 실제 비밀번호로 변경해주세요

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true